### ISSUE TITLE
I tried to edit it but it disappeared

### ISSUE THREAD

**Issue by DavidWillie1106** [CodoPixel/code_editor#15] opened 2023-08-03 09:47 UTC
![Dingtalk_20230803174440](https://github.com/ThomasGysemans/code_editor/assets/67700115/578689cb-873b-49a3-9609-ce349adce7a4)
![Dingtalk_20230803174502](https://github.com/ThomasGysemans/code_editor/assets/67700115/42b4bcf7-cd85-4260-962d-c5f0000a2550)

**Comment by ThomasGysemans** [comment] 2023-08-03 09:48
You have to give some more code if you want help

**Comment by DavidWillie1106** [comment] 2023-08-03 09:51
ChangeNotifierProvider<PagesScope>.value(
            value: bloc.pageScope,
            child: Consumer<PagesScope>(builder: (_, scope, __) {
              String? naem = bloc.editController?.text;
              List<FileEditor> files = [
                FileEditor(
                  name: bloc.searchController?.text,
                  language: "html",
                  code: naem, // [code] needs a string
                ),
              ];

              EditorModel model = EditorModel(
                files: files,
              );
              return Padding(
                padding: const EdgeInsets.symmetric(vertical: 30),
                child: CodeEditor(
                  model: model,
                  formatters: const ["html"],
                ),
              );
            }),
          ),

**Comment by ThomasGysemans** [comment] 2023-08-03 09:54
All right, it's probably a problem from the auto-formatter, try removing the `formatters` property from `CodeEditor` and tell me if it works please. If it works, please give me a copy of the text you tried to write in this file so that I can investigate on the issue further.

**Comment by transmissionhub** [comment] 2023-08-06 11:07
@ThomasGysemans I encountered the same problem and I have removed the "formatters". But the problem is still here.

**Comment by Zhanweelee** [comment] 2023-08-06 11:08
@ThomasGysemans  I encountered the same problem and I have removed the "formatters". But the problem is still here.

**Comment by ThomasGysemans** [comment] 2023-08-06 11:49
But I have no way to know what the problem is because you don't give code, or what was written in the file when you tried to save it. I need details.

**Comment by Zhanweelee** [comment] 2023-08-07 02:43
@ThomasGysemans  I found the root cause that I wrongly put the "model = EditorModel(...)" in the "build" function. So it will be initialized every time the page state changes. I fixed it by moving it to class level. Thx

**Comment by ThomasGysemans** [comment] 2023-08-07 07:35
Maybe I should update the example then, thank you

**Comment by ThomasGysemans** [comment] 2023-08-07 08:02
I hope that the version [2.1.0](https://github.com/ThomasGysemans/code_editor/commit/1d9a8893c8eb61d6e3ff70b5d1be2df60d7d58f5) fixes the issue.

**Closed as completed by ThomasGysemans** 2023-08-07 08:02 UTC
